[cerebrium.deployment]
name = "mtailor"
python_version = "3.10"
disable_auth = false
include = ['main.py', 'model.py', 'Dockerfile', 'pyproject.toml', 'poetry.lock', 'models/*.onnx']
exclude = ['.*', '**/__pycache__/**', 'tests/**', '*.pyc']

[cerebrium.runtime.custom]
port = 8005
healthcheck_endpoint = "/health"
dockerfile_path = "./Dockerfile"

[cerebrium.hardware]
cpu = 2.0
memory = 12.0
compute = "CPU"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 30
replica_concurrency = 1
response_grace_period = 900
scaling_metric = "concurrency_utilization"
scaling_target = 100
scaling_buffer = 0
roll_out_duration_seconds = 0
